# Introdunction to Numpy

In [2]:
import numpy as np


## 1.创建ndarray
### 直接从其他序列对象创建


In [9]:
a = np.array(1)  # 0维数组（标量）
b = np.array([1, 2])  # 1维数组（向量）
c = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])  # 2维数组（矩阵）
d = np.array([[[1, 2, 3], [4, 5, 6]], [[4, 5, 6], [1, 2, 3]]])  # 3维数组（张量）
# 多维数组需要用嵌套的列表创建

In [10]:
print(d)

[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [1 2 3]]]


In [ ]:
# 查看ndarray的属性
print(d.shape) #形状数
print(d.ndim) #维度数
print(d.size) #总大小
print(d.dtype) # 数据类型

In [6]:
# 一个常见的错误，就是调用array的时候传入多个数字参数，而不是提供单个数字的列表类型作为参数。
# a = np.array(1,2,3,4)    # WRONG
a = np.array([1,2,3,4])  # RIGHT
a

array([1, 2, 3, 4])

### 通过占位符创建
通常，数组的元素最初是未知的，但它的大小是已知的。因此，NumPy提供了几个函数来创建具有初始占位符内容的数组。这就减少了数组增长的必要，因为数组增长的操作花费很大。



In [6]:
c = np.ones( (2,3) )  # 全1数组，同时指定数据类型
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
print(c.size) #总大小

6


In [7]:
a = np.zeros( (3,4) ) # 全零数组
b = np.ones( (2,3,4), dtype=np.int16 )  # 全1数组，同时指定数据类型
c = np.empty( (2,3) ) # 空数组。初始内容是随机的，取决于内存的状态。

In [8]:
print(b.size) #总大小

24


### 通过arange/linespace创建序列数组
为了创建数字组成的数组，NumPy提供了一个类似于range的函数，该函数返回数组而不是列表。

当arange与浮点参数一起使用时，由于有限的浮点精度，通常不可能预测所获得的元素的数量。出于这个原因，通常最好使用linspace函数来接收我们想要的元素数量的函数，而不是步长（step）：


In [9]:
print(np.arange( 10, 30, 5 )) # 从10开始，到30中止，每5个一个元素

[10 15 20 25]


In [10]:
print(np.arange( 0, 2, 0.3 )) # 从0开始，到2中止，每0.3个一个元素

[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [11]:
print(np.linspace( 0, 2, 9 ))# 从0开始，到2中止，共9个元素，均匀间隔。

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


### 随机数组

In [3]:
# 随机数组
a = np.random.rand(10)# 均匀随机数
b = np.random.randn(2,10)# 正态分布的随机数
c = np.random.randint(0,100,10)# 随机整数

print("a =",a)
print("\nb =",b)
print("\nc =",c)

a = [0.16110574 0.09187564 0.54508811 0.15119824 0.04130149 0.75296484
 0.44654662 0.82556085 0.68720135 0.63380953]

b = [[-1.25717218  0.31944364  1.52720278  1.40149051  0.36562316 -1.63577418
  -0.96914904 -0.83363193 -1.3850974  -0.08500545]
 [-0.63481459  2.13156941  1.67686295 -0.78939931 -1.00125998  0.6902149
   0.25629112  1.24970254 -0.02816182  1.4714527 ]]

c = [96  4 48 92 33 43 84 10  2 38]


## 2.访问
索引与切片

In [13]:
# 一维
a = np.arange(10)
print(a)
print(a[9])
print(a[5:-2])

[0 1 2 3 4 5 6 7 8 9]
9
[5 6 7]


In [15]:
# 二维
c = np.random.randint(0,100,[4,3])# 二维随机整数
print(c)
print("\n",c[3]) # 默认按照行索引
print("\n",c[:,1]) # 按照列索引

[[75 35 40]
 [35 39  1]
 [90 39 50]
 [69 87 39]]

 [69 87 39]

 [35 39 39 87]


In [29]:
# numpy的索引支持层级索引；index可以重复
nd = np.arange(10,20)
print(nd)                  # array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
print(nd[[0,0,0,1,0,0]])   # array([10, 10, 10, 11, 10, 10]) 里面是索引，使用列表的方式可以重复的去获取

[10 11 12 13 14 15 16 17 18 19]
[10 10 10 11 10 10]


## 3.常用函数

In [18]:
arr = np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
print(arr.sum())  # 求和
print(arr.max())  # 最大值
print(arr.min())  # 最小值

print(arr.mean())  # 平均值
print(arr.std())  # 标准差
print(arr.var())  # 方差

# 4.运算

## 4.1 逐元素运算

In [20]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
# 内置数学函数：按照元素逐位运算
print(np.square(arr),'\n') #平方
print(np.exp(arr),'\n') #指数
print(np.sin(arr),'\n') #正弦函数

[[ 1  4  9]
 [16 25 36]] 

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]] 

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]] 



In [22]:
# 相同元素的数组运算：按照元素逐位运算
print(arr+arr,'\n')
print(arr-arr,'\n')
print(arr*arr,'\n')
print(arr/arr,'\n')

[[ 2  4  6]
 [ 8 10 12]] 

[[0 0 0]
 [0 0 0]] 

[[ 1  4  9]
 [16 25 36]] 

[[1. 1. 1.]
 [1. 1. 1.]] 



## 4.2 广播
不同形状的数组之间的运算方式

广播的第一个规则是，如果所有输入数组不具有相同数量的维度，则将“1”重复地预先添加到较小数组的形状，直到所有数组具有相同数量的维度。

广播的第二个规则确保沿特定维度的大小为1的数组表现为具有沿该维度具有最大形状的数组的大小。假定数组元素的值沿着“广播”数组的那个维度是相同的。

一些例子：
```
A      (2d array):  5 x 4
B      (1d array):      1
Result (2d array):  5 x 4

A      (2d array):  5 x 4
B      (1d array):      4
Result (2d array):  5 x 4

A      (3d array):  15 x 3 x 5
B      (3d array):  15 x 1 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 1
Result (3d array):  15 x 3 x 5
```


In [37]:
arr1 = np.arange(7)
print(arr1)

[0 1 2 3 4 5 6]


In [38]:
# 标量10广播到了其他元素上
arr2 = arr1+10
print(arr2)

[10 11 12 13 14 15 16]


In [42]:
# 矩阵与向量运算
arr1 = np.arange(4).reshape(-1,1)
arr1 = np.tile(arr1,3)
arr2 = np.arange(4)

print(arr1)
print(arr2)

[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]]
[0 1 2 3]


In [43]:
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [27]:
arr1 + arr2.reshape(4,1)

array([[0, 0, 0],
       [2, 2, 2],
       [4, 4, 4],
       [6, 6, 6]])

### 3.3 线性代数运算

In [6]:
arr1 = np.arange(1,9).reshape(2,4)
arr2 = np.arange(1,13).reshape(4,3)
print(arr1)
print(arr2)

arr1.dot(arr2) # 矩阵乘法

[[1 2 3 4]
 [5 6 7 8]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


array([[ 70,  80,  90],
       [158, 184, 210]])

In [29]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
arr1.T #矩阵转置

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

# 5. 改变矩阵形状
## 5.1 改变自身形状

In [7]:
a = np.floor(10*np.random.random((3,4))) # 随机创建3x4矩阵

print(a.ravel()) # returns the array, flattened)
print(a)

[6. 2. 5. 7. 5. 8. 1. 6. 1. 9. 9. 7.]
[[6. 2. 5. 7.]
 [5. 8. 1. 6.]
 [1. 9. 9. 7.]]


In [32]:
print(a.reshape(6,2)) # 重新组织形状

[[6. 2.]
 [3. 2.]
 [4. 1.]
 [0. 1.]
 [4. 7.]
 [2. 8.]]


In [46]:
print(a.T)  # returns the array, transposed

[[8. 8. 4.]
 [1. 7. 8.]
 [3. 5. 4.]
 [8. 5. 2.]]


## 5.2 堆叠数组

In [2]:
# 几个数组可以沿不同的轴堆叠在一起，例如：
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))

print(a)
print(b)

[[2. 5.]
 [9. 7.]]
[[9. 9.]
 [5. 7.]]


In [3]:
np.vstack((a,b)) #

array([[2., 5.],
       [9., 7.],
       [9., 9.],
       [5., 7.]])

In [4]:
np.hstack((a,b))

array([[2., 5., 9., 9.],
       [9., 7., 5., 7.]])

In [5]:
# concatenate 允许可选参数给出连接应发生的轴的编号。
np.concatenate((a,b), 0)

array([[2., 5.],
       [9., 7.],
       [9., 9.],
       [5., 7.]])

In [6]:
#axis=1代表按照行进行拼接
np.concatenate((a,b), axis=1)

array([[2., 5., 9., 9.],
       [9., 7., 5., 7.]])