# Introdunction to Numpy
## 1. 创建ndarray
- 从其他序列对象创建
- 通过占位符创建
- 用`arange/linespace`创建
- 通过随机数组创建

## 2. 访问
- 索引和切片
- 布尔索引 Boolean Indexing

## 3. 常用函数

## 4. 运算
- 逐元素运算
- 广播 Broadcasting
- 线性代数运算
- `Scipy` for linear algebras and solving equations

## 5. 改变矩阵形状
- 堆叠 `stack`
- 拆分 `split`

In [1]:
import numpy as np

# 1.创建ndarray
## 1.1 直接从其他序列对象创建


In [2]:
a = np.array(1)  # 0维数组（标量）
b = np.array([1, 2])  # 1维数组（向量）
c = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])  # 2维数组（矩阵）
d = np.array([[[1, 2, 3], [4, 5, 6]], [[4, 5, 6], [1, 2, 3]]])  # 3维数组（张量）
# 多维数组需要用嵌套的列表创建

In [3]:
print(d)

[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [1 2 3]]]


## 1.2 Array Attributes

In [4]:
# 查看ndarray的属性
print(d.shape) #形状数
print(d.ndim) #维度数
print(d.size) #总大小
print(d.dtype) # 数据类型

(2, 2, 3)
3
12
int32


In [5]:
# 一个常见的错误，就是调用array的时候传入多个数字参数，而不是提供单个数字的列表类型作为参数。
# a = np.array(1,2,3,4)    # WRONG
a = np.array([1,2,3,4])  # RIGHT
a

array([1, 2, 3, 4])

## 1.3 Array placeholder content 通过占位符创建
通常，数组的元素最初是未知的，但它的大小是已知的。因此，NumPy提供了几个函数来创建具有初始占位符内容的数组。这就减少了数组增长的必要，因为数组增长的操作花费很大。



In [6]:
c = np.ones( (2,3) )  # 全1数组，同时指定数据类型
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
print(c.size) #总大小

6


In [8]:
a = np.zeros( (3,4) ) # 全零数组
b = np.ones( (2,3,4), dtype=np.int16 )  # 全1数组，同时指定数据类型
c = np.empty( (2,3) ) # 空数组。初始内容是随机的，取决于内存的状态。

In [9]:
print(b.size) #总大小

24


## 1.4 通过arange/linespace创建序列数组
为了创建数字组成的数组，NumPy提供了一个类似于range的函数，该函数返回数组而不是列表。

当arange与浮点参数一起使用时，由于有限的浮点精度，通常不可能预测所获得的元素的数量。出于这个原因，通常最好使用linspace函数来接收我们想要的元素数量的函数，而不是步长（step）：


In [10]:
print(np.arange( 10, 30, 5 )) # 从10开始，到30中止，每5个一个元素

[10 15 20 25]


In [11]:
print(np.arange( 0, 2, 0.3 )) # 从0开始，到2中止，每0.3个一个元素

[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [12]:
print(np.linspace( 0, 2, 9 ))# 从0开始，到2中止，共9个元素，均匀间隔。

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


## 1.5 随机数组

In [13]:
# 随机数组
a = np.random.rand(10)# 均匀随机数
b = np.random.randn(2,10)# 正态分布的随机数
c = np.random.randint(0,100,10)# 随机整数

print("a =",a)
print("\nb =",b)
print("\nc =",c)

a = [0.65229683 0.04226338 0.80305813 0.87101749 0.01388949 0.40847916
 0.25984045 0.80026927 0.17156492 0.63007386]

b = [[ 0.23275346 -0.26652801  0.85402624 -1.04545331  0.46623138 -0.02316769
  -2.08745861 -0.30060483 -0.15922988  0.25076146]
 [ 0.08135395  0.80393762 -1.92737528  0.8732087  -0.44250327  1.3602853
   0.54491461  0.8955891   0.04103108  0.05710027]]

c = [96 97 20 35 78 54 88 70 43 15]


# 2.访问
## 2.1索引与切片

In [14]:
# 一维
a = np.arange(10)
print(a)
print(a[9])
print(a[5:-2])

[0 1 2 3 4 5 6 7 8 9]
9
[5 6 7]


In [15]:
# 二维
c = np.random.randint(0,100,[4,3])# 二维随机整数
print(c)
print("\n",c[3]) # 默认按照行索引
print("\n",c[:,1]) # 按照列索引

[[71  0 90]
 [89  4 62]
 [57 50 34]
 [72 76 67]]

 [72 76 67]

 [ 0  4 50 76]


In [16]:
# numpy的索引支持层级索引；index可以重复
nd = np.arange(10,20)
print(nd)                  # array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
print(nd[[0,0,0,1,0,0]])   # array([10, 10, 10, 11, 10, 10]) 里面是索引，使用列表的方式可以重复的去获取

[10 11 12 13 14 15 16 17 18 19]
[10 10 10 11 10 10]


## 2.2 布尔索引 Boolean Indexing

In [28]:
a[a>5]

array([6, 7, 8, 9])

In [30]:
a[a==1]=3
a

array([0, 3, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
a==3

array([False,  True, False,  True, False, False, False, False, False,
       False])

# 3.常用函数

In [17]:
arr = np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
print(arr.sum())  # 求和
print(arr.max())  # 最大值
print(arr.min())  # 最小值

print(arr.mean())  # 平均值
print(arr.std())  # 标准差
print(arr.var())  # 方差

145
19
10
14.5
2.8722813232690143
8.25


# 4.运算

## 4.1 逐元素运算

In [19]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
# 内置数学函数：按照元素逐位运算
print(np.square(arr),'\n') #平方
print(np.exp(arr),'\n') #指数
print(np.sin(arr),'\n') #正弦函数

[[ 1  4  9]
 [16 25 36]] 

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]] 

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]] 



In [21]:
# 相同元素的数组运算：按照元素逐位运算
print(arr+arr,'\n')
print(arr-arr,'\n')
print(arr*arr,'\n')
print(arr/arr,'\n')

[[ 2  4  6]
 [ 8 10 12]] 

[[0 0 0]
 [0 0 0]] 

[[ 1  4  9]
 [16 25 36]] 

[[1. 1. 1.]
 [1. 1. 1.]] 



## 4.2 广播
不同形状的数组之间的运算方式

- 广播的第一个规则是，如果所有输入数组不具有相同数量的维度，则将重复地填充较小数组，直到所有数组具有相同数量的维度。

- 广播的第二个规则确保沿特定维度的大小为1的数组表现为具有沿该维度具有最大形状的数组的大小。假定数组元素的值沿着“广播”数组的那个维度是相同的。

- 如果不满足上述两条规则，则会抛出`ValueError`的报错

一些例子：
```
A      (2d array):  5 x 4
B      (1d array):      1
Result (2d array):  5 x 4

A      (2d array):  5 x 4
B      (1d array):      4
Result (2d array):  5 x 4

A      (3d array):  15 x 3 x 5
B      (3d array):  15 x 1 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 1
Result (3d array):  15 x 3 x 5
```


In [22]:
arr1 = np.arange(7)
print(arr1)

[0 1 2 3 4 5 6]


In [23]:
# 标量10广播到了其他元素上
arr2 = arr1+10
print(arr2)

[10 11 12 13 14 15 16]


In [24]:
# 矩阵与向量运算
arr1 = np.arange(4).reshape(-1,1)
arr1 = np.tile(arr1,3)
arr2 = np.arange(4)

print(arr1)
print(arr2)

[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]]
[0 1 2 3]


In [25]:
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [26]:
arr1 + arr2.reshape(4,1)

array([[0, 0, 0],
       [2, 2, 2],
       [4, 4, 4],
       [6, 6, 6]])

In [46]:
arr3=arr1.reshape(4,1)
arr3

ValueError: cannot reshape array of size 12 into shape (4,1)

## 4.3 线性代数运算

In [2]:
arr1 = np.arange(1,9).reshape(2,4)
arr2 = np.arange(1,13).reshape(4,3)
print(arr1)
print(arr2)

arr1.dot(arr2) # 矩阵乘法

[[1 2 3 4]
 [5 6 7 8]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


array([[ 70,  80,  90],
       [158, 184, 210]])

In [3]:
arr1.T #矩阵转置

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [4]:
np.diag(arr2) #提取对角线

array([1, 5, 9])

In [5]:
np.diag(np.diag(arr2))

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [6]:
np.trace(arr2) # return the sum along diagonals of the array

15

## 4.4 Scipy for Linear Algebra

In [8]:
import scipy.linalg

In [11]:
arr3=np.array([[-2,3],[4,5]])
scipy.linalg.det(arr3)

-22.0

In [12]:
scipy.linalg.inv(arr3)

array([[-0.22727273,  0.13636364],
       [ 0.18181818,  0.09090909]])

### Solve systems of linear equations
用线性代数方法解线性方程组
- 直接调用Scipy的`solve`函数求解
- 用线性代数公式求解

In [13]:
A=np.array([[2,4,6],[1,-3,-9],[8,5,-7]])
b=np.array([4,-11,1])
scipy.linalg.solve(A,b)

array([-8.52173913,  9.69565217, -2.95652174])

In [14]:
np.dot(scipy.linalg.inv(A),b)

array([-8.52173913,  9.69565217, -2.95652174])

# 5. 改变矩阵形状
## 5.1 Shape and Reshape 改变自身形状

In [ ]:
a = np.floor(10*np.random.random((3,4))) # 随机创建3x4矩阵

print(a.ravel()) # returns the array, flattened)
print(a)

In [ ]:
print(a.reshape(6,2)) # 重新组织形状

In [ ]:
print(a.T)  # returns the array, transposed

## 5.2 Stacking 堆叠数组

In [32]:
# 几个数组可以沿不同的轴堆叠在一起，例如：
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))

print(a)
print(b)

[[7. 9.]
 [4. 3.]]
[[0. 2.]
 [1. 3.]]


In [33]:
np.vstack((a,b)) #

array([[7., 9.],
       [4., 3.],
       [0., 2.],
       [1., 3.]])

In [34]:
np.hstack((a,b))

array([[7., 9., 0., 2.],
       [4., 3., 1., 3.]])

In [35]:
# concatenate 允许可选参数给出连接应发生的轴的编号。
np.concatenate((a,b), 0)

array([[7., 9.],
       [4., 3.],
       [0., 2.],
       [1., 3.]])

In [36]:
#axis=1代表按照行进行拼接
np.concatenate((a,b), axis=1)

array([[7., 9., 0., 2.],
       [4., 3., 1., 3.]])

## 5.3 Splitting

In [38]:
c=np.hstack((a,b))
c

array([[7., 9., 0., 2.],
       [4., 3., 1., 3.]])

In [40]:
np.hsplit(c,4)

[array([[7.],
        [4.]]),
 array([[9.],
        [3.]]),
 array([[0.],
        [1.]]),
 array([[2.],
        [3.]])]

In [41]:
np.vsplit(c,2)

[array([[7., 9., 0., 2.]]), array([[4., 3., 1., 3.]])]